---
title: "p"
output:
  word_document: default
  html_document: default
date: '2022-04-30'
---

```{r}
library(class)
library(MASS)
library(e1071)
library(tree)
library(randomForest)
```


```{r}
df <- read.csv("final_data.csv",header=F)
head(df)
```


```{r}
for(i in 1:408){
  names(df)[i] <- paste("Col", i)
}

head(df, 10)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
df.centered <- scale(df, scale = T, center = T)
```


```{r}
pca_data <- prcomp(df.centered)
summary(pca_data)
```


```{r}

```

```{r}
library("factoextra")
```



```{r}
get_eig(pca_data)
```


```{r}
eig.val <- get_eigenvalue(pca_data)
head(eig.val, 10)
```


```{r}
pca_data$rotation[1:10, 1:10]
```
```{r}
fviz_eig(pca_data, addlabels = T, ncp = 15)
```
```{r}


```

```{r}
pcs = data.frame(pca_data$x)
PCA = pca_data$sdev^2
names(PCA) = paste0('PC', cor$pcs)
qcc::pareto.chart(df$PCA)

```



```{r}
PCA <- pca_data$sdev[1:10]^2
names(PCA) <- paste("PC", c(1:10))
```

```{r}
df.pca <- pca_data$x[, 1:3]
df.pca <- as.data.frame(df.pca)
dim(df.pca)
```

```{r}
head(df.pca)
```

```{r}
summary(df.pca)
```


```{r}
install.packages('MSQC', dependencies=TRUE, repos='http://cran.rstudio.com/')
```


```{r}
library(qcr)
```


```{r}
  c1 <- mqcs.mcusum(df.pca, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c1)
print(c1)
print(violation)
```


```{r}
itr_points1=c1$violation
n1=df.pca[-itr_points1,]
 c2 <- mqcs.mcusum(n1, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c2)
print(c2)
print(violation)
```


```{r}
itr_points1=c2$violation
n2=n1[-itr_points1,]
 c3 <- mqcs.mcusum(n2, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c3)
print(c3)
```



```{r}
itr_points1=c3$violations
n3=n2[-itr_points1,]
 c4 <- mqcs.mcusum(n3, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c4)
print(c4)
```


```{r}
itr_points1=c4$violations
n4=n3[-itr_points1,]
 c5 <- mqcs.mcusum(n4, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c5)
print(c5)
```


```{r}
itr_points1=c5$violations
n5=n4[-itr_points1,]
 c6 <- mqcs.mcusum(n5, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c6)
print(c6)
```


```{r}
itr_points1=c6$violations
n6=n5[-itr_points1,]
 c7 <- mqcs.mcusum(n6, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c7)
print(c7)
```


```{r}
itr_points1=c7$violations
n7=n6[-itr_points1,]
 c8 <- mqcs.mcusum(n7, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(c8)
print(c8)
```


```{r}
library(qcc)
data(n7)
(t1 <- mqcc(n7, type = "T2", confidence.level = 0.9973))
```


```{r}
violation=t1$violations$beyond.limits
n8=n7[-violation,]
data(n8)
(t2 <- mqcc(n8, type = "T2", confidence.level = 0.9973))
```


```{r}
violation=t2$violations$beyond.limits
n9=n8[-violation,]
data(n9)
(t3 <- mqcc(n9, type = "T2", confidence.level = 0.9973))
```

```{r}

```

```{r}

 s1 <- mqcs.mcusum(n9, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(s1)
print(s1)

```



```{r}
itr_points1=s1$violations
n10=n9[-itr_points1,]
 s2 <- mqcs.mcusum(n10, type='mcusum', k =1, h =5.5, method = "sw",plot = T)
summary(s2)
print(s2)
```

```{r}

data(n10)
(s3 <- mqcc(n10, type = "T2", confidence.level = 0.9973))

```



```{r}
#final in control data sets.
print(n10)

```

```{r}
for(i in 1:3){
  names(n10)[i] <- paste("X", i)
}

head(n10,255)

```

```{r}


```

```{r}


```














